### PR TITLE
fixes for build issues on linux

### LINKED ISSUE #45: Libunifex does not compile on Linux
It appears that there is a namespace called `linux`. For some reason, Clang 9 #define's linux to be 1 on my platform (Ubuntu 18.04). I'm using the clang-9 from apt.llvm.org. Error below:

/usr/bin/clang++-9   -I../source/../include -Iinclude -stdlib=libc++ -std=gnu++2a -MD -MT source/CMakeFiles/unifex.dir/linux/monotonic_clock.cpp.o -MF source/CMakeFiles/unifex.dir/linux/monotonic_clock.cpp.o.d -o source/CMakeFiles/unifex.dir/linux/monotonic_clock.cpp.o -c ../source/linux/monotonic_clock.cpp
In file included from ../source/linux/monotonic_clock.cpp:16:
../source/../include/unifex/linux/monotonic_clock.hpp:24:11: error: expected identifier or '{'
namespace linux {
          ^
<built-in>:392:15: note: expanded from here
#define linux 1
              ^

### PR DESCRIPTION
**Pull request by kirkshoop**
this should fix #45 in addition to the issues found once that was fixed.

### CODE REVIEW

File: include/unifex/detail/intrusive_heap.hpp [hunk 1]
```diff
@@ -32,7 +32,7 @@ class intrusive_heap {
       assert(item->*Prev == nullptr);
     }
     while (item != nullptr) {
-      std::printf("- %p\n", item);
+      printf("- %p\n", item);
```
Comment (lewissbaker) [inline include/unifex/detail/intrusive_heap.hpp]: I think this was missing `#include <cstdio>` rather than being incorrectly scoped.
Although I'd like to replace this with some kind of `TRACE()` macro at some point that allows it to be compiled out if required.

File: include/unifex/linux/io_uring_context.hpp [hunk 2]
```diff
@@ -42,7 +44,7 @@
 #include <sys/uio.h>
 
 namespace unifex {
-namespace linux {
+namespace linuxos {
```
Comment (lewissbaker) [inline include/unifex/linux/io_uring_context.hpp]: I was debating what to call this namespace.
I think linuxos is a reasonable tradeoff. 👍 

Do we change the directory name to match, though?

File: cmake/unifex_flags.cmake [hunk 3]
```diff
@@ -27,3 +27,15 @@ if(CXX_MEMORY_RESOURCE_HAVE_PMR)
 else()
   set(UNIFEX_NO_MEMORY_RESOURCE TRUE)
 endif()
+
+# Probe for libUring support
+find_package(LibUring COMPONENTS Experimental Final)
```
Comment (lewissbaker) [inline cmake/unifex_flags.cmake]: Do we need the Experimental/Final parameters here?

These are added to the find_package() calls above to indicate that they should search for both experimental/final versions of the standard-library features. I don't think that really applies to liburing.

File: include/unifex/linux/io_uring_context.hpp (hunk 2 above)
Comment (kirkshoop) [reply include/unifex/linux/io_uring_context.hpp]: I don't think so - at least for this diff.
